#!/usr/bin/env python3

import sys, fileinput, csv
import datetime as dt
import dateutil.tz as dutz
from common import *

with open_default_db() as d, fileinput.input() as input:
    reader = csv.reader(input)
    next(reader, None)
    for line in reader:
        client, project, _, _, start_txt, end_txt, tz_txt, *_ = line
        tz    = dutz.gettz(tz_txt)
        start = dt.datetime.fromisoformat(start_txt).astimezone(tz)
        end   = dt.datetime.fromisoformat(end_txt).astimezone(tz)
        entry = Entry(client, project, start, end)
        try:
            d.add_entry(entry)
        except OverlappingEntriesError as e:
            e.print_error()
            print(file=sys.stderr)
